name: cozy_games
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5

  firebase_auth: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
